# Generated by Django 4.2 on 2023-04-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Scene',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('describtion', models.CharField(max_length=255)),
                ('weather', models.CharField(max_length=255)),
                ('road', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('objecter', models.CharField(max_length=255)),
                ('action_objecter', models.CharField(max_length=255)),
            ],
        ),
    ]
