# Generated by Django 4.2 on 2023-04-29 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
