# Generated by Django 4.2 on 2023-05-02 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0005_alter_report_ego_trajectory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='scenename',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scenes.scene'),
        ),
    ]
