# Generated by Django 4.2 on 2023-05-02 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0006_alter_report_scenename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='scenename',
        ),
    ]
