# Generated by Django 4.2 on 2023-05-02 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0007_remove_report_scenename'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='scenename',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scenes.scene'),
        ),
    ]
