# Generated by Django 4.2 on 2023-05-04 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0009_module_scene_modules'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='mdescribtion',
            field=models.CharField(max_length=255, null='111'),
            preserve_default='111',
        ),
        migrations.AddField(
            model_name='module',
            name='mname',
            field=models.CharField(max_length=255, null='111'),
            preserve_default='111',
        ),
    ]
