# Generated by Django 4.2 on 2023-05-04 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0010_module_mdescribtion_module_mname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='module',
            old_name='mdescribtion',
            new_name='describtion',
        ),
        migrations.RenameField(
            model_name='module',
            old_name='mname',
            new_name='name',
        ),
    ]
