# Generated by Django 4.2 on 2023-05-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0012_rename_ego_trajectory_report_data_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='file',
            field=models.FileField(null=True, upload_to='scenicFile'),
        ),
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
