# Generated by Django 4.2 on 2023-05-02 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0002_scene_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='file',
            field=models.FileField(null=True, upload_to='scenicFile'),
        ),
    ]
