# Generated by Django 4.2 on 2023-05-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0003_scene_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scenename', models.CharField(max_length=255)),
                ('ego_trajectory', models.BinaryField(null=True)),
                ('objecter_trajectory', models.BinaryField(null=True)),
            ],
        ),
    ]
