# Generated by Django 4.2 on 2023-08-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scenes', '0013_report_file_report_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='scene',
            name='video',
            field=models.FileField(blank='true', null=True, upload_to='videos', verbose_name='视频'),
        ),
    ]
